### ISSUE TITLE
Run Tork workers on K8s environment

### ISSUE THREAD

**Issue by ppcololo** [runabol/tork#188]
Statement: run `N` workers inside K8s as pods
Run Tork inside K8s is ideal option for me, because I can easily scale workers.
For now Tork requires Docker inside and it means I can run it only virtual machines or I have to use somehow `dind` images to run docker inside docker.

Is it possible to disable run tasks inside docker containers if I'm already inside K8s?
Something like skip `image` field which is required?
In this case we will have to options how to run tasks:
* inside docker container on VM
* inside K8s pod directly without docker

**Comment by runabol** [comment]
Interesting. So if I understand correctly your intention is to bundle the Tork binary and all other the binaries you'd need for your tasks and then have the tasks run directly on the same container/pod that Tork is running. Is this correct?

If so, then my initial approach is:

1. Creating a new [Runtime](https://github.com/runabol/tork/blob/main/internal/runtime/runtime.go) implementation which essentially uses [os/exec](https://pkg.go.dev/os/exec) to execute tasks on the host rather than use Docker. 
3. Use a new configuration parameter (maybe `runtime.type=host`) to configure the worker to use the `HostRuntime` implementation.

Since this isn't really Kubernetes-specific, the implementation can probably be used anywhere where the operator wants tasks to directly run on the Tork host. The main caveat is that you lose task isolation but since this is an opt-in feature and not the default runtime, I think that's acceptable. 

Does this sound reasonable?

**Comment by ppcololo** [comment]
> Does this sound reasonable?
Yes, will be great to have an option to use host runtime environment.

**Comment by runabol** [comment]
@ppcololo Cool. I can put something together probably later tonight.

**Comment by gaby** [comment]
> @gaby I believe this is similar to a request you've made as well.

Yes, it's very similar.

**Comment by runabol** [comment]
@gaby @ppcololo mind taking a look: https://github.com/runabol/tork/pull/189 ?

**Comment by ppcololo** [comment]
LGTM @runabol 
thanks a lot!
