### ISSUE TITLE
Tork API expose

### ISSUE THREAD

**Issue by ppcololo** [runabol/tork#191]
Hello, 
I'm trying to use Tork API for creating Jobs.
I'm using `tork` + `tork-web` and for me it was little bit tricky how to create Jobs via API besause I sent API requests to `web-ui` port and only after some time I realised that I have to send them to `coordinator` port.
In this case we have to expose 2 ports outside: `coordinator` port + `web-ui` port.
Is it possible to allow send API request to `web-ui` and it will transfer it to `tork` directly just to not expose `coordinator` outside?

**Comment by runabol** [comment]
You could probably make it work by calling the web UI API route handlers, but I would HIGHLY advise against it as it's not intended for that. 

Is this a security concert to not expose the coordinator port?

**Comment by ppcololo** [comment]
Yes, we can expose `web-ui` to the internet but secure it via `nginx htpasswd` and dont want to expose another one port and secure it also.
But I think this is a common approach when we have `frontend` with some REST API endpoints and `backend` with logic. (before you had only backend with exposed API)

**Comment by runabol** [comment]
I see. If the intention is to use the web ui to submit jobs then you should be good with just setting the [BACKEND_URL](https://github.com/runabol/tork-web/blob/93cb5c1fe3981d53f8cc55951887f82559b1ac83/.env.development#L1) to point to the Coordinator. Since the UI is making server-side calls then you shouldn't have to expose the Coordinator.

**Comment by ppcololo** [comment]
thanks
